### ISSUE TITLE
关于profile第二人称转换

### ISSUE THREAD

**Issue by 27182812** [morecry/CharacterChat#2]
你好，我看profile_trans/query_data.py这个文件应该会把profile重写为第二人称，存储在profile_trans_output.json里，但是我看示例文件里好像很少是第二人称。

**Comment by morecry** [comment]
第二人称profile在每个example的profile_trans字段里，在比较靠后的位置
![image](https://github.com/morecry/CharacterChat/assets/45983142/c1d452be-21bf-4b36-a484-8c779187d6d6)

**Comment by 27182812** [comment]
哦哦对的 我刚也发现了 准备来关的 感谢您的回复
